import { I_Experience } from "@/src/types/type";

export const words = [
  "Design Engineer",
  "FullStack Developer",
  "Solana Developer",
  "Frontend Specialist",
];

export const experienceData: I_Experience[] = [
  {
    company_link: "https://www.beiyo.in/",
    company_logo: "/assets/beiyo.png",
    company_name: "Beiyo",
    duration: "2024 - 2025",
    job_title: "FullStack Developer",
    description: "",
  },
  {
    company_link: "#",
    company_logo: "/assets/upwork-icon.png",
    company_name: "Freelance",
    duration: "2023 - Present",
    job_title: "FullStack Developer",
    description: "",
  },
];

export const projects = [
   {
    title: "Paths AI",
    description: "Structured learning journeys created by AI.",
    tech: ["AI","trpc","redis","Next.js"],
    status: "In Development",
    year: "2025",
    link: "https://paths.shrid.in",
    code: "https://github.com/shridmishra/paths",
    imageSrc: "/projects/paths.png",
    video:"/projects/video/paths.mp4"
  },
   {
    title: "CRM",
    description: "Customer Relationship Management app.",
    tech: ["Next.js","TypeScript","Drizzle"],
    status: "In Development",
    year: "2025",
    link: "https://crm.shrid.in",
    code: "https://github.com/shridmishra",
    imageSrc: "/projects/crm.png",
    video:"/projects/video/crm.mp4"
  },
  {
    title: "Project Manager",
    description: "Project Management app with clean UI dashboards.",
    tech: ["Next.js","TypeScript","Drizzle"],
    status: "In Development",
    year: "2025",
    link: "https://projects.shrid.in",
    code: "https://github.com/shridmishra/project-management",
    imageSrc: "/projects/projects.png",
    video:"/projects/video/projects.mp4"
  },{
    title: "Practice JS",
    description: "Leetcode like questions but for FullStack Development.",
    tech: ["Next.js", "TypeScript", "MongoDB"],
    status: "Live",
    year: "2025",
    link: "https://practicejs.shrid.in",
    code: "https://github.com/shridmishra/practicejs",
    imageSrc: "/projects/practicejs.png",
    video: "/projects/video/practicejs.mp4",
  },
  {
    title: "AnimeFlix",
    description: "Anime streaming platform with NeoBrutalism.",
    tech: ["NeoBrutalism", "YouTube API"],
    status: "In Progress",
    year: "2025",
    link: "https://animeflix.shrid.in",
    code: "https://github.com/shridmishra/animeflix",
    imageSrc: "/projects/animeflix.png",
    video: "/projects/video/animeflix.mp4",

  },
  {
    title: "Grocery Store",
    description: "Shopping app with cart, admin panel and payments.",
    tech: ["React", "Stripe", "MongoDB"],
    status: "Live",
    year: "2025",
    link: "https://grocery.shrid.in",
    code: "https://github.com/shridmishra/grocery-store",
    imageSrc: "/projects/grocery.png",
    video: "/projects/video/grocery.mp4",


  },
 
  {
    title: "MediChain",
    description: "Solana platform for secure health data.",
    tech: ["Next.js", "TypeScript", "Solana", "Anchor", "PostgreSQL"],
    status: "In Development",
    year: "2025",
    link: "https://medichain.shrid.in",
    code: "https://github.com/shridmishra/medichain",
    imageSrc: "/projects/medichain.png",
  },
{
    title: "Blogs",
    description: "Personal blogging platform with rich text editor.",
    tech: ["TipTap", "MDX", "TypeScript"],
    status: "In Development",
    year: "2025",
    link: "https://blogs.shrid.in/post/new",
    code: "https://github.com/shridmishra/blogs",
    imageSrc: "/projects/blogs.png",
  },
  {
    title: "Crypto Explorer",
    description: "Real-time cryptocurrency data visualization.",
    tech: [
      "React",
      "TypeScript",
      "Node.js",
      "Chart.js",
      "CoinGecko API",
      "Axios",
    ],
    status: "Live",
    year: "2025",
    link: "https://crypto.shrid.in",
    code: "https://github.com/shridmishra/crypto-explorer",
    imageSrc: "/projects/crypto.png",
  },
  
  {
    title: "Notes",
    description: "Note app with collaboration features.",
    tech: ["React", "JavaScript", "Node.js", "Express", "Socket.io", "MongoDB"],
    status: "Live",
    year: "2025",
    link: "https://notes.shrid.in",
    code: "https://github.com/shridmishra/sgsits-notes",
    imageSrc: "/projects/notes.png",
  },
  {
    title: "Landing Page",
    description: "SEO-optimized marketing landing template.",
    tech: ["Next.js", "TypeScript", "Framer"],
    status: "Live",
    year: "2025",
    link: "https://landing-page-shrid.vercel.app/",
    code: "https://github.com/shridmishra/landing-page",
    imageSrc: "/projects/landing.png",
  },

  {
    title: "Old Portfolio",
    description: "Personal portfolio with modern design.",
    tech: [
      "Next.js",
      "TypeScript",
      "React",
      "Tailwind CSS",
      "Framer Motion",
      "Vercel",
    ],
    status: "Live",
    year: "2025",
    link: "https://portfolio.shrid.in",
    code: "https://github.com/shridmishra/shridmishra-v1",

    imageSrc: "/projects/portfolio.png",
  },
  {
    title: "Finboard",
    description: "Finance dashboard with live stock and widgets.",
    tech: ["ReCharts", "Zustland", "RGL"],
    status: "In Progress",
    year: "2025",
    link: "https://finboard.shrid.in",
    code: "https://github.com/shridmishra/finboard",
    imageSrc: "/projects/finboard.png",
  },
  {
    title: "Solana Contract",
    description: "Smart contract for SPL token staking.",
    tech: ["Rust", "Solana", "Anchor", "TypeScript", "Mocha"],
    status: "Live",
    year: "2025",
    link: "https://github.com/shridmishra/solana-contracts",
    code: "https://github.com/shridmishra/solana-contracts",
    imageSrc: "/projects/solana.png",
  },
];
